single thumbnailer instance
invideoio/Transcoder pull request #9
Opened 2022-05-04 09:24 UTC by dhruv2295

2022-05-04 11:15 UTC, sahilbajaj commented on lib/src/main/java/com/otaliastudios/transcoder/internal/Tracks.kt
> +    val strategies: TrackMap<TrackStrategy>,
I believe, we can avoid this.

2022-05-04 16:06 UTC, sahilbajaj requested changes
Some minor changes

2022-05-04 16:06 UTC, sahilbajaj commented on lib/src/main/java/com/otaliastudios/transcoder/internal/CustomSegments.kt
> +            if (currentSegment != null) {
Redundant null check

2022-05-04 16:06 UTC, sahilbajaj commented on lib/src/main/java/com/otaliastudios/transcoder/internal/CustomSegments.kt
> +            val reversed = segmentMap.entries.associate { (k, v) -> v to k }
Either we should create this when segments get updated
Or
Simply use some utility to query by value

2022-05-04 16:10 UTC, sahilbajaj reviewed
Some comments

2022-05-04 16:10 UTC, sahilbajaj commented on lib/src/main/java/com/otaliastudios/transcoder/internal/thumbnails/DefaultThumbnailsEngine.kt
> +                log.i("Updating pipeline positions for segment Index#$index absoluteUs=${positions.joinToString { it.first.toString() }}, and stubs $stubs")
We should just use a flag. So it's hard to pass these logs to develop

2022-05-07 19:46 UTC, dhruv2295 commented on lib/src/main/java/com/otaliastudios/transcoder/internal/CustomSegments.kt
> +            if (currentSegment != null) {
done

2022-05-07 19:46 UTC, dhruv2295 commented on lib/src/main/java/com/otaliastudios/transcoder/internal/thumbnails/DefaultThumbnailsEngine.kt
> +                log.i("Updating pipeline positions for segment Index#$index absoluteUs=${positions.joinToString { it.first.toString() }}, and stubs $stubs")
done

2022-05-07 20:10 UTC, sahilbajaj commented on lib/src/main/java/com/otaliastudios/transcoder/internal/CustomSegments.kt
> +    fun release() = destroySegment()
Let's create a new method destroySegments()

2022-05-07 20:39 UTC, sahilbajaj approved these changes

2022-05-07 20:39 UTC, merged